const Branches = [
    {value:"Electrical",label:"Electrical"},
    {value:"Mechanical",label:"Mechanical"},
    {value:"Aerospace",label:"Aerospace"},
    {value:"Civil",label:"Civil"},
    {value:"Electronics",label:"Electronics"},
    {value:"Metallurgy",label:"Metallurgy"},
    {value:"Mining",label:"Mining"},
    {value:"Communication",label:"Communication"},
    {value:"Food",label:"Food"},
    {value:"Instrumentation",label:"Instrumentation"},
    {value:"Computer Science",label:"Computer Science"},
    {value:"Chemical",label:"Chemical"},
    {value:"Industrial",label:"Industrial"},
    {value:"Production",label:"Production"},
    {value:"Control",label:"Control"},
    {value:"Materials",label:"Materials"},
    {value:"Energy",label:"Energy"},
    {value:"Metallurgical",label:"Metallurgical"},
    {value:"Materials",label:"Materials"},
    {value:"Data Science",label:"Data Science"},
    {value:"Bio Medical",label:"Bio Medical"},
    {value:"Ceramic",label:"Ceramic"},
    {value:"Biomedical",label:"Biomedical"},
    {value:"Agricultural",label:"Agricultural"},
    {value:"Mechatronics",label:"Mechatronics"},
    {value:"Environmental",label:"Environmental"},
    {value:"Mineral",label:"Mineral"},
    {value:"Machinery",label:"Machinery"},
    // "Petroleum",
    // "Biological",
    // "Naval Architecture",
    // "Bio",
    // "Materials Science",
    // "Production",
    // "Infrastructure",
    // "Computer Science",
    // "Material Science",
    // "Biotechnology",
    // "Computational",
    // "Computer",
    // "Electronics System",
    // "Biochemical",
    // "Pharmaceutical",
    // "Systems",
    // "Manufacturing Science",
    // "Mining Safety",
    // "Ocean",
    // "Environmental Science",
  ];

  export default Branches