const Branches = [
  "Select Branches",
  "Mechanical",
  "Aerospace",
  "Civil",
  "Electronics",
  "Metallurgy",
  "Mining",
  "Communication",
  "Food",
  "Instrumentation",
  "Computer Science",
  "Chemical",
  "Industrial",
  "Production",
  "Control",
  "Materials",
  "Energy",
  "Metallurgical",
  "Materials",
  "Data Science",
  "Bio Medical",
  "Ceramic",
  "Biomedical",
  "Agricultural",
  "Mechatronics",
  "Environmental",
  "Mineral",
  "Machinery",
  "Petroleum",
  "Biological",
  "Naval Architecture",
  "Bio",
  "Materials Science",
  "Production",
  "Infrastructure",
  "Computer Science",
  "Material Science",
  "Biotechnology",
  "Computational",
  "Computer",
  "Electronics System",
  "Biochemical",
  "Pharmaceutical",
  "Systems",
  "Manufacturing Science",
  "Mining Safety",
  "Ocean",
  "Environmental Science",
];

export default Branches;
